### ISSUE TITLE
Allow this mod to work with AquaAcrobatics.

### ISSUE THREAD

**Issue by MagmaSlime123** [jbredwards/Subaquatic#16]
Title.

AquaAcrobatics adds more 1.13 features, such as the new swimming, crawling, underwater fog, bubble columns, and water coloring. Allow this mod's features to work with it correctly. For example, the fog/extra vision doesn't seem to function correctly.

Also, add a config for toggling unwanted features. I don't need Fish Buckets that have BOP poison or other odd liquids in them, doesn't make sense.

![2023-03-06_15 56 51](https://user-images.githubusercontent.com/51277766/223276159-0093831b-530a-4590-883d-2642d9351911.png)

**Comment by jbredwards** [comment]
The aqua acrobatics fog density issue should now be fixed in dev. As for the fish buckets, here's my reply to someone else with the same request: https://github.com/jbredwards/Subaquatic/issues/5#issuecomment-1431572498 (the mentioned config will have bop poison blacklisted by default since I forgot that existed xd)

**Comment by MagmaSlime123** [comment]
Ah.

**Comment by jbredwards** [comment]
fixed in v1.1.0
