### ISSUE TITLE
Breaks other mods foliage colors.

### ISSUE THREAD

**Issue by MagmaSlime123** [jbredwards/Subaquatic#21]
Title.

![2023-03-07_12 45 28](https://user-images.githubusercontent.com/51277766/223535637-2fed9ec7-deb6-479b-9b57-3003d0a94abb.png)

**Comment by jbredwards** [comment]
this mod does nothing to influence foliage colors, does the issue persist when this mod is removed from the pack?

**Comment by MagmaBro123** [comment]
No, I'm guessing Quark's greener grass hates this mod, but I'm not sure.

**Comment by MagmaSlime123** [comment]
It's apparently caused by Quark's greener grass feature.
Not sure if FluidloggedAPI or this mod is the issue, though.

**Comment by jbredwards** [comment]
this is a quark issue, below screenshot is with only quark, bop, and nature's compass. I did find a setting in quark's config file that lets you add blocks that get the greener grass color though, so the issue is fixable!
![2023-03-08_23 38 12](https://user-images.githubusercontent.com/47703524/223918643-5fa67ca0-9957-4e85-a477-633b822459bc.png)
