### ISSUE TITLE
The fish in bucket add other fluid incorrectly

### ISSUE THREAD

**Issue by HaHaWTH** [jbredwards/Subaquatic#5]
Install some Tech mods and this mod "compact" with these fluids with some problems like "Fish in a molten iron bucket"
![copyy](https://user-images.githubusercontent.com/102713261/219010665-5974f323-1e3a-425f-8f87-016f9c823378.png)

**Comment by HaHaWTH** [comment]
This mod also causes serious FPS lag,after remove this mod and its dependencies this problem wont appear anymore

**Comment by jbredwards** [comment]
> The fish in bucket add other fluid incorrectly

This is intentional, the logic is that if the fish can survive in the fluid block while in the world (if the fluid block uses `Material.WATER`), then the fish should also be able to survive in the fluid bucket, right? A quick way to test if a fluid block is using `Material.WATER` is to see if the player can swim in it like water. I'll add a config option in the next update to blacklist certain fish bucket fluids though :)

> This mod also causes serious FPS lag,after remove this mod and its dependencies this problem wont appear anymore

There is known rendering lag with forge's fluid rendering system (used by fluidlogged api), to get around that install [CensoredASM](https://www.curseforge.com/minecraft/mc-mods/lolasm) and [Nothirium](https://www.curseforge.com/minecraft/mc-mods/nothirium).

**Comment by H-QueerCoded** [comment]
It would be really nice to have a whitelist option for the fluids used. In a large modpack there can be a lot of fluids that use `Material.WATER` when they probably shouldn't. Rather than listing every fluid fish shouldn't be in, it would be a lot more convenient to be able to specify the few that actually make sense.
