### ISSUE TITLE
Crash when look at items of galacticraft in JEI or creative tab

### ISSUE THREAD

**Issue by magcicada** [jbredwards/Subaquatic#69]
Crash when look at items of galacticraft in JEI or creative tab
[crash-2023-10-16_02.04.39-client.txt](https://github.com/jbredwards/Subaquatic/files/12917336/crash-2023-10-16_02.04.39-client.txt)

**Comment by magcicada** [comment]
This issue is the same as #51

**Comment by jbredwards** [comment]
this can be fixed by using the latest version of subaquatic

**Comment by magcicada** [comment]
So can you push the new version jar file to curseforge? I have downloaded it at modrinth.

**Comment by jbredwards** [comment]
> So can you push the new version jar file to curseforge?

No, all new files will be modrinth only until further notice. The reasons I'm leaving my old curseforge projects up are for archive purposes, and to not potentially mess up any existing curseforge modpacks. If you're asking because you're making a curseforge exclusive modpack, you can use [File Director](https://www.curseforge.com/minecraft/mc-mods/filedirector) to have your pack download subaquatic at runtime!

> I have downloaded it at modrinth.

The crashlog says you're using v1.1.0, the most recent version is v1.2.1 (which you can download [here](https://modrinth.com/mod/subaquatic/version/1.2.1))
